export const items = [
  {
    _id: "item1",
    main_category: "Electronics",
    title: "Premium Wireless Headphones",
    average_rating: 4.7,
    rating_number: 253,
    item_index: 1001,
  },
  {
    _id: "item2",
    main_category: "Electronics",
    title: "Smart Fitness Tracker",
    average_rating: 4.5,
    rating_number: 189,
    item_index: 1002,
  },
  {
    _id: "item3",
    main_category: "Home & Kitchen",
    title: "Automatic Coffee Maker",
    average_rating: 4.3,
    rating_number: 127,
    item_index: 1003,
  },
  {
    _id: "item4",
    main_category: "Home & Kitchen",
    title: "Non-Stick Cookware Set",
    average_rating: 4.6,
    rating_number: 98,
    item_index: 1004,
  },
  {
    _id: "item5",
    main_category: "Clothing",
    title: "Men's Casual Jacket",
    average_rating: 4.2,
    rating_number: 76,
    item_index: 1005,
  },
  {
    _id: "item6",
    main_category: "Clothing",
    title: "Women's Running Shoes",
    average_rating: 4.8,
    rating_number: 215,
    item_index: 1006,
  },
  {
    _id: "item7",
    main_category: "Books",
    title: "The Art of Programming",
    average_rating: 4.9,
    rating_number: 67,
    item_index: 1007,
  },
  {
    _id: "item8",
    main_category: "Books",
    title: "Modern Web Development",
    average_rating: 4.7,
    rating_number: 42,
    item_index: 1008,
  },
  {
    _id: "item9",
    main_category: "Electronics",
    title: "4K Smart TV",
    average_rating: 4.6,
    rating_number: 178,
    item_index: 1009,
  },
  {
    _id: "item10",
    main_category: "Electronics",
    title: "Wireless Gaming Mouse",
    average_rating: 4.4,
    rating_number: 156,
    item_index: 1010,
  },
  {
    _id: "item11",
    main_category: "Home & Kitchen",
    title: "Robot Vacuum Cleaner",
    average_rating: 4.5,
    rating_number: 112,
    item_index: 1011,
  },
  {
    _id: "item12",
    main_category: "Home & Kitchen",
    title: "Air Purifier",
    average_rating: 4.3,
    rating_number: 89,
    item_index: 1012,
  },
  {
    _id: "item13",
    main_category: "Clothing",
    title: "Women's Winter Coat",
    average_rating: 4.7,
    rating_number: 134,
    item_index: 1013,
  },
  {
    _id: "item14",
    main_category: "Clothing",
    title: "Men's Dress Shoes",
    average_rating: 4.5,
    rating_number: 78,
    item_index: 1014,
  },
  {
    _id: "item15",
    main_category: "Books",
    title: "Data Science Fundamentals",
    average_rating: 4.8,
    rating_number: 56,
    item_index: 1015,
  },
  {
    _id: "item16",
    main_category: "Books",
    title: "History of Innovation",
    average_rating: 4.6,
    rating_number: 34,
    item_index: 1016,
  },
  {
    _id: "item17",
    main_category: "Sports",
    title: "Professional Tennis Racket",
    average_rating: 4.7,
    rating_number: 87,
    item_index: 1017,
  },
  {
    _id: "item18",
    main_category: "Sports",
    title: "Mountain Bike",
    average_rating: 4.9,
    rating_number: 65,
    item_index: 1018,
  },
  {
    _id: "item19",
    main_category: "Beauty",
    title: "Skincare Gift Set",
    average_rating: 4.4,
    rating_number: 123,
    item_index: 1019,
  },
  {
    _id: "item20",
    main_category: "Beauty",
    title: "Professional Hair Dryer",
    average_rating: 4.6,
    rating_number: 98,
    item_index: 1020,
  },
  {
    _id: "item21",
    main_category: "Toys",
    title: "Educational Building Blocks",
    average_rating: 4.8,
    rating_number: 145,
    item_index: 1021,
  },
  {
    _id: "item22",
    main_category: "Toys",
    title: "Remote Control Car",
    average_rating: 4.5,
    rating_number: 112,
    item_index: 1022,
  },
  {
    _id: "item23",
    main_category: "Furniture",
    title: "Ergonomic Office Chair",
    average_rating: 4.7,
    rating_number: 78,
    item_index: 1023,
  },
  {
    _id: "item24",
    main_category: "Furniture",
    title: "Modern Coffee Table",
    average_rating: 4.6,
    rating_number: 56,
    item_index: 1024,
  },
]
